---
title: "RQA"
subtitle: "Recurrence Quantification Analysis"
author: "Maas van Steenbergen"
date: today
format: 
     revealjs:
          theme: serif
jupyter: julia-1.9
---

## Introduction
-    In social sciences research, we usually treat variation in data as something to control for.
-    Think of a typical ANOVA:
     1.   We derive averages for our dependent variable. By estimating the expected value we aim to control for all variation in our signal. 
     2.   We divide our sample into groups, and aim to average out all variation caused by changes beyond our variables of interest.

## Introduction
-    This is a very effective research strategy. The experiment is the ultimate example! 
     1.   It allows us to make inferences about the average strength of the effect of a manipulation.
     2.   It allows us to disentangle the effect on a dependent variable by a manipulation of independent variables between pre-defined groups.
-    In short, a well-administered experimental or correlational study, is nothing to jeer at.

## Dynamics
-    But there are a lot of aspects that are difficult to capture by relying on aggregates.
     1.   For example, how does mood fluctuate over the day?
     2.   How does your pupil move to scan their visual field?
     3.   How do people move through their environment?
     4.   How do schizophrenic symptoms appear over time?
-    These questions go into *dynamics*: the forces and motions that characterize a system.

## Dynamics
-    The "forces" that lead to a change in mood, or that decide how you scan the room with your eyes, are difficult to model or analyze:
     1.   These forces are numerous.
     2.   Interactions between these forces are numerous.
     3.   Interactions between these forces are non-linear.
     4.   It is impossible to infer the behaviour of the larger system by exclusively studying its components (*emergent* behaviour).

## Complex Systems
-    Systems like these are found in every applied research field, and seem to have a surprising number of common properties (and a larger number of differences).
-    *Complex Systems* research is involved with studying the properties of systems where its behaviour is consistent with these properties (e.g., numerous elements, non-linear interactions, emergent properties).
-    Do note that scientists do not agree on an exact formal definition.
-    Complex systems tend to be intrinsically more difficult to study and model.

## Recurrence Quantification Analysis
-    There are many different methods to study the underlying dynamics of complex system.
-    But we'll focus on only one: Recurrence Quantification Analysis
-    This is the basic technique 

##

-    When doing research on mood, or other measures that use self-report, we often rely on fairly *course-grained* measures.
-    We also tend to rely on *ordinal* scaling: there is only a han.
-    That's because we simply don't 

## Open questions
